version: '3.8'

services:
  # OnlyOffice Document Server
  onlyoffice-documentserver:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice-documentserver
    restart: always
    ports:
      - "8080:80"
    environment:
      - JWT_ENABLED=false
      - WOPI_ENABLED=false
      - USE_UNAUTHORIZED_CONNECTION=true
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data
      - onlyoffice_log:/var/log/onlyoffice
      - onlyoffice_cache:/var/lib/onlyoffice
      - ./production-linux-custom.json:/etc/onlyoffice/documentserver/production-linux.json
    networks:
      - onlyoffice-network

  # Python File Server
  fileserver:
    build: ./fileserver
    container_name: onlyoffice-fileserver
    restart: always
    ports:
      - "8081:8000"
    volumes:
      - ./fileserver/uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - onlyoffice-network

networks:
  onlyoffice-network:
    driver: bridge

volumes:
  onlyoffice_data:
  onlyoffice_log:
  onlyoffice_cache:
